"""add_assessment_report_table

Revision ID: 20251018_003230
Revises: f9a8b7c6d5e4
Create Date: 2025-10-18 00:32:30.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20251018_003230'
down_revision = 'f9a8b7c6d5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_identifier', sa.String(length=255), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('conversation_quality', sa.String(length=50), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('protective_factors', sa.JSON(), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_reports_id'), 'assessment_reports', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_reports_session_identifier'), 'assessment_reports', ['session_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_reports_session_identifier'), table_name='assessment_reports')
    op.drop_index(op.f('ix_assessment_reports_id'), table_name='assessment_reports')
    op.drop_table('assessment_reports')
    # ### end Alembic commands ###
