"""initial_schema

Revision ID: 21cc7471d905
Revises: 
Create Date: 2025-10-10 07:15:12.906524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cc7471d905'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_usage', 'session_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verification_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_verification_attempt', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_verification_attempt')
    op.drop_column('users', 'email_verification_attempts')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_token')
    op.alter_column('conversation_usage', 'session_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
