"""add_email_verification_fields

Revision ID: f5253d32245b
Revises: 3b22d871e4d5
Create Date: 2025-10-09 20:45:41.340265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5253d32245b'
down_revision: Union[str, Sequence[str], None] = '3b22d871e4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verification_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_verification_attempt', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_column('users', 'last_verification_attempt')
    op.drop_column('users', 'email_verification_attempts')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###
